import { jsPDF } from 'jspdf';

export const generatePlayerPDF = (playerData, championMastery) => {
  const doc = new jsPDF();

  // Add a title
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('League of Legends Player Report', 10, 20);

  // Add a horizontal line
  doc.setLineWidth(0.5);
  doc.line(10, 25, 200, 25);

  // Add player details
  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(12);
  if (playerData && playerData.puuid) {
    doc.text(`Summoner Name: ${playerData.gameName || '[Unknown]'}`, 10, 40);
    doc.text(`Region: ${playerData.tagLine || '[Unknown]'}`, 10, 50);
    doc.text(`PUUID: ${playerData.puuid}`, 10, 60);
  } else {
    doc.text('Summoner Name: [Placeholder]', 10, 40);
    doc.text('Region: [Placeholder]', 10, 50);
    doc.text('PUUID: [Placeholder]', 10, 60);
  }

  // Add top 3 champions
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('Top 3 Most-Played Champions:', 10, 80);

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(12);
  if (championMastery && championMastery.length > 0) {
    championMastery.slice(0, 3).forEach((champion, index) => {
      doc.text(`${index + 1}. Champion ID: ${champion.championId}`, 10, 90 + index * 20);
      doc.text(`   Champion Points: ${champion.championPoints}`, 10, 95 + index * 20);
      doc.text(`   Champion Level: ${champion.championLevel}`, 10, 100 + index * 20);
    });
  } else {
    doc.text('No champion mastery data available.', 10, 90);
  }

  // Add footer
  doc.setFontSize(10);
  doc.text('Generated by League of Legends PDF-Creator', 10, 280);

  const pdfBlob = doc.output('blob');
  return URL.createObjectURL(pdfBlob); // Return the Blob URL
};